//! Typed client wrapper for the kapi API server.
//!
//! Provides [`TypedClient<T>`] for type-safe CRUD operations on resources.

use std::marker::PhantomData;

use serde::{Serialize, de::DeserializeOwned};

use kapi_core::{ListOptions, ObjectMeta, ResourceKey, StoredObject, SystemMetadata};

use crate::client::KapiClient;
use crate::error::ClientError;

/// Errors that can occur when using the typed client.
#[derive(Debug, thiserror::Error)]
pub enum TypedError {
    /// Error from the underlying HTTP client.
    #[error(transparent)]
    Client(#[from] ClientError),

    /// JSON serialization or deserialization failure.
    #[error("serialization error: {0}")]
    Serialization(#[from] serde_json::Error),
}

/// Trait for types that can be used with [`TypedClient`].
///
/// Implement this trait on wrapper structs generated by `kapibuild api generate`.
/// The trait provides the bridge between typed Rust structs and the raw
/// [`StoredObject`] format used by the kapi server.
pub trait TypedResource: Sized + Send + Sync + 'static {
    /// The spec type for this resource.
    type Spec: Serialize + DeserializeOwned;

    /// The status type for this resource.
    type Status: Serialize + DeserializeOwned;

    /// Returns the [`ResourceKey`] identifying this resource type.
    fn key() -> ResourceKey;

    /// Constructs a resource from its component parts.
    fn from_parts(
        metadata: ObjectMeta,
        system: SystemMetadata,
        spec: Self::Spec,
        status: Option<Self::Status>,
    ) -> Self;

    /// Returns a reference to the resource's metadata.
    fn metadata(&self) -> &ObjectMeta;

    /// Returns a reference to the resource's system metadata.
    fn system(&self) -> &SystemMetadata;

    /// Returns a reference to the resource's spec.
    fn spec(&self) -> &Self::Spec;

    /// Returns a reference to the resource's status, if present.
    fn status(&self) -> Option<&Self::Status>;
}

/// A type-safe client for CRUD operations on kapi resources.
///
/// Wraps [`KapiClient`] and provides typed operations for any resource type
/// that implements [`TypedResource`].
///
/// # Example
///
/// ```ignore
/// let client = KapiClient::new("http://localhost:8080")?;
/// let typed = TypedClient::<Widget>::new(client);
///
/// // Create a new widget
/// let meta = ObjectMeta { name: "my-widget".into(), ..Default::default() };
/// let spec = WidgetSpec { color: "red".into() };
/// let widget = typed.create(Some("default"), &meta, &spec).await?;
///
/// // Get the widget back
/// let fetched = typed.get(Some("default"), "my-widget").await?;
/// ```
#[derive(Debug, Clone)]
pub struct TypedClient<T: TypedResource> {
    client: KapiClient,
    _marker: PhantomData<T>,
}

impl<T: TypedResource> TypedClient<T> {
    /// Creates a new typed client wrapping the given [`KapiClient`].
    pub fn new(client: KapiClient) -> Self {
        Self { client, _marker: PhantomData }
    }

    /// Returns a reference to the underlying [`KapiClient`].
    pub fn inner(&self) -> &KapiClient {
        &self.client
    }

    /// Creates a new resource.
    ///
    /// Extracts metadata and spec from the typed resource, serializes them to
    /// JSON, and sends them to the server. The server assigns system metadata
    /// and returns the created resource.
    ///
    /// # Errors
    ///
    /// Returns [`TypedError::Client`] for HTTP/API errors.
    /// Returns [`TypedError::Serialization`] if spec serialization fails.
    pub async fn create(&self, namespace: Option<&str>, resource: &T) -> Result<T, TypedError> {
        let key = T::key();
        let meta = resource.metadata();
        let spec_value = serde_json::to_value(resource.spec())?;
        let stored = self.client.create(&key, namespace, meta, &spec_value).await?;
        Self::stored_to_typed(stored)
    }

    /// Retrieves a resource by name.
    ///
    /// Fetches the [`StoredObject`] from the server and deserializes it into
    /// the typed resource.
    ///
    /// # Errors
    ///
    /// Returns [`TypedError::Client`] for HTTP/API errors.
    /// Returns [`TypedError::Serialization`] if deserialization fails.
    pub async fn get(&self, namespace: Option<&str>, name: &str) -> Result<T, TypedError> {
        let key = T::key();
        let stored = self.client.get(&key, namespace, name).await?;
        Self::stored_to_typed(stored)
    }

    /// Updates an existing resource.
    ///
    /// Serializes the typed resource to a [`StoredObject`] and sends it to the
    /// server. Returns the updated resource.
    ///
    /// # Errors
    ///
    /// Returns [`TypedError::Client`] for HTTP/API errors.
    /// Returns [`TypedError::Serialization`] if serialization fails.
    pub async fn update(&self, namespace: Option<&str>, resource: &T) -> Result<T, TypedError> {
        let stored = Self::typed_to_stored(resource)?;
        let updated = self.client.update(namespace, &stored).await?;
        Self::stored_to_typed(updated)
    }

    /// Deletes a resource by name.
    ///
    /// Returns the deleted resource.
    ///
    /// # Errors
    ///
    /// Returns [`TypedError::Client`] for HTTP/API errors.
    /// Returns [`TypedError::Serialization`] if deserialization fails.
    pub async fn delete(&self, namespace: Option<&str>, name: &str) -> Result<T, TypedError> {
        let key = T::key();
        let stored = self.client.delete(&key, namespace, name).await?;
        Self::stored_to_typed(stored)
    }

    /// Lists resources of this type.
    ///
    /// Fetches all resources (optionally filtered by namespace and list options)
    /// and deserializes each into the typed resource.
    ///
    /// # Errors
    ///
    /// Returns [`TypedError::Client`] for HTTP/API errors.
    /// Returns [`TypedError::Serialization`] if any item fails to deserialize.
    pub async fn list(
        &self,
        namespace: Option<&str>,
        opts: &ListOptions,
    ) -> Result<Vec<T>, TypedError> {
        let key = T::key();
        let response = self.client.list(&key, namespace, opts).await?;
        response.items.into_iter().map(Self::stored_to_typed).collect()
    }

    // ------------------------------------------------------------------
    // Conversion helpers
    // ------------------------------------------------------------------

    /// Converts a [`StoredObject`] into the typed resource.
    ///
    /// # Errors
    ///
    /// Returns [`TypedError::Serialization`] if the spec or status fields
    /// cannot be deserialized into their typed counterparts.
    fn stored_to_typed(stored: StoredObject) -> Result<T, TypedError> {
        let spec: T::Spec = serde_json::from_value(stored.spec)?;
        let status: Option<T::Status> = match stored.status {
            Some(value) => Some(serde_json::from_value(value)?),
            None => None,
        };
        Ok(T::from_parts(stored.metadata, stored.system, spec, status))
    }

    /// Converts a typed resource into a [`StoredObject`].
    ///
    /// # Errors
    ///
    /// Returns [`TypedError::Serialization`] if the spec or status fields
    /// cannot be serialized to JSON.
    fn typed_to_stored(resource: &T) -> Result<StoredObject, TypedError> {
        let key = T::key();
        let metadata = resource.metadata().clone();
        let system = resource.system().clone();
        let spec = serde_json::to_value(resource.spec())?;
        let status = match resource.status() {
            Some(s) => Some(serde_json::to_value(s)?),
            None => None,
        };
        Ok(StoredObject { key, metadata, system, spec, status })
    }
}

// ------------------------------------------------------------------
// Tests
// ------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use serde::{Deserialize, Serialize};
    use std::collections::HashMap;

    // Mock resource types for testing
    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
    #[serde(rename_all = "camelCase")]
    struct TestSpec {
        color: String,
        size: u32,
    }

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
    #[serde(rename_all = "camelCase")]
    struct TestStatus {
        ready: bool,
        count: u32,
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct TestResource {
        metadata: ObjectMeta,
        system: SystemMetadata,
        spec: TestSpec,
        #[serde(skip_serializing_if = "Option::is_none")]
        status: Option<TestStatus>,
    }

    impl TypedResource for TestResource {
        type Spec = TestSpec;
        type Status = TestStatus;

        fn key() -> ResourceKey {
            ResourceKey {
                group: "test.io".to_string(),
                version: "v1".to_string(),
                kind: "TestResource".to_string(),
            }
        }

        fn from_parts(
            metadata: ObjectMeta,
            system: SystemMetadata,
            spec: Self::Spec,
            status: Option<Self::Status>,
        ) -> Self {
            Self { metadata, system, spec, status }
        }

        fn metadata(&self) -> &ObjectMeta {
            &self.metadata
        }

        fn system(&self) -> &SystemMetadata {
            &self.system
        }

        fn spec(&self) -> &Self::Spec {
            &self.spec
        }

        fn status(&self) -> Option<&Self::Status> {
            self.status.as_ref()
        }
    }

    fn test_metadata(name: &str) -> ObjectMeta {
        ObjectMeta {
            name: name.to_string(),
            namespace: Some("default".to_string()),
            labels: HashMap::new(),
            annotations: HashMap::new(),
            finalizers: Vec::new(),
        }
    }

    fn test_stored_object(
        name: &str,
        spec: serde_json::Value,
        status: Option<serde_json::Value>,
    ) -> StoredObject {
        StoredObject {
            key: TestResource::key(),
            metadata: test_metadata(name),
            system: SystemMetadata::initial(),
            spec,
            status,
        }
    }

    // --- Conversion tests ---

    #[test]
    fn stored_to_typed_with_status() {
        let spec = serde_json::json!({
            "color": "red",
            "size": 42
        });
        let status = serde_json::json!({
            "ready": true,
            "count": 5
        });
        let stored = test_stored_object("test-1", spec, Some(status));

        let typed = TypedClient::<TestResource>::stored_to_typed(stored).unwrap();

        assert_eq!(typed.metadata.name, "test-1");
        assert_eq!(typed.spec.color, "red");
        assert_eq!(typed.spec.size, 42);
        assert!(typed.status.is_some());
        assert!(typed.status.as_ref().unwrap().ready);
        assert_eq!(typed.status.as_ref().unwrap().count, 5);
    }

    #[test]
    fn stored_to_typed_without_status() {
        let spec = serde_json::json!({
            "color": "blue",
            "size": 100
        });
        let stored = test_stored_object("test-2", spec, None);

        let typed = TypedClient::<TestResource>::stored_to_typed(stored).unwrap();

        assert_eq!(typed.metadata.name, "test-2");
        assert_eq!(typed.spec.color, "blue");
        assert_eq!(typed.spec.size, 100);
        assert!(typed.status.is_none());
    }

    #[test]
    fn stored_to_typed_invalid_spec() {
        let spec = serde_json::json!({
            "color": "green"
            // missing "size" field
        });
        let stored = test_stored_object("test-3", spec, None);

        let result = TypedClient::<TestResource>::stored_to_typed(stored);
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), TypedError::Serialization(_)));
    }

    #[test]
    fn typed_to_stored_with_status() {
        let resource = TestResource {
            metadata: test_metadata("test-4"),
            system: SystemMetadata::initial(),
            spec: TestSpec { color: "yellow".to_string(), size: 200 },
            status: Some(TestStatus { ready: false, count: 10 }),
        };

        let stored = TypedClient::<TestResource>::typed_to_stored(&resource).unwrap();

        assert_eq!(stored.metadata.name, "test-4");
        assert_eq!(stored.spec["color"], "yellow");
        assert_eq!(stored.spec["size"], 200);
        assert!(stored.status.is_some());
        assert_eq!(stored.status.as_ref().unwrap()["ready"], false);
        assert_eq!(stored.status.as_ref().unwrap()["count"], 10);
    }

    #[test]
    fn typed_to_stored_without_status() {
        let resource = TestResource {
            metadata: test_metadata("test-5"),
            system: SystemMetadata::initial(),
            spec: TestSpec { color: "purple".to_string(), size: 50 },
            status: None,
        };

        let stored = TypedClient::<TestResource>::typed_to_stored(&resource).unwrap();

        assert_eq!(stored.metadata.name, "test-5");
        assert_eq!(stored.spec["color"], "purple");
        assert_eq!(stored.spec["size"], 50);
        assert!(stored.status.is_none());
    }

    #[test]
    fn roundtrip_conversion() {
        let original = TestResource {
            metadata: test_metadata("test-6"),
            system: SystemMetadata::initial(),
            spec: TestSpec { color: "orange".to_string(), size: 75 },
            status: Some(TestStatus { ready: true, count: 3 }),
        };

        let stored = TypedClient::<TestResource>::typed_to_stored(&original).unwrap();
        let recovered = TypedClient::<TestResource>::stored_to_typed(stored).unwrap();

        assert_eq!(original.metadata.name, recovered.metadata.name);
        assert_eq!(original.metadata.namespace, recovered.metadata.namespace);
        assert_eq!(original.system.resource_version, recovered.system.resource_version);
        assert_eq!(original.system.generation, recovered.system.generation);
        assert_eq!(original.spec.color, recovered.spec.color);
        assert_eq!(original.spec.size, recovered.spec.size);
        assert_eq!(original.status.is_some(), recovered.status.is_some());
        if let (Some(orig), Some(rec)) = (original.status.as_ref(), recovered.status.as_ref()) {
            assert_eq!(orig.ready, rec.ready);
            assert_eq!(orig.count, rec.count);
        }
    }

    // --- Resource key tests ---

    #[test]
    fn resource_key_returns_correct_key() {
        let key = TestResource::key();
        assert_eq!(key.group, "test.io");
        assert_eq!(key.version, "v1");
        assert_eq!(key.kind, "TestResource");
    }

    // --- TypedClient construction tests ---

    #[test]
    fn typed_client_new() {
        let client = KapiClient::new("http://localhost:8080").unwrap();
        let typed = TypedClient::<TestResource>::new(client.clone());
        // Verify we can access the inner client
        let inner = typed.inner();
        assert_eq!(
            inner.build_url(&TestResource::key(), None, ""),
            "http://localhost:8080/apis/test.io/v1/TestResource"
        );
    }

    // --- Error conversion tests ---

    #[test]
    fn typed_error_from_client_error() {
        let client_err = ClientError::ApiError {
            status: 404,
            code: "NotFound".to_string(),
            message: "resource not found".to_string(),
        };
        let typed_err: TypedError = client_err.into();
        assert!(matches!(typed_err, TypedError::Client(_)));
        let msg = format!("{}", typed_err);
        assert!(msg.contains("404"));
        assert!(msg.contains("NotFound"));
    }

    #[test]
    fn typed_error_from_serialization_error() {
        let serde_err = serde_json::from_str::<TestSpec>("invalid json").unwrap_err();
        let typed_err: TypedError = serde_err.into();
        assert!(matches!(typed_err, TypedError::Serialization(_)));
        let msg = format!("{}", typed_err);
        assert!(msg.contains("serialization error"));
    }
}
