//! Namespace resource — built-in core type registration and lifecycle helpers.
//!
//! Namespace is a first-class cluster-scoped resource with `kind: "Namespace"`,
//! `group: "kapi.io"`, `version: "v1"`. The schema is registered at server
//! startup and the `"default"` namespace is auto-created.
//!
//! This module owns:
//! - [`namespace_schema_json`] — the minimal schema JSON for Namespace
//! - [`register_namespace_schema`] — stores the Schema object so the
//!   SchemaRegistry can lazy-compile it like any other kind
//! - [`bootstrap_default_namespace`] — ensures the "default" Namespace object
//!   exists, creating it if not
//!
//! `Namespace` is always cluster-scoped; all operations pass `namespace: None`
//! to the store. The `"default"` namespace cannot be deleted (rejected by
//! [`crate::object::service::ObjectService::delete`]).

use std::sync::Arc;

use serde_json::{Value, json};
use tracing::info;

use crate::error::AppError;
use crate::event::EventPublisher;
use crate::object::schema_service::SchemaService;
use crate::object::types::ObjectMeta;
use crate::schema::{DEFAULT_NAMESPACE, NAMESPACE_GROUP, NAMESPACE_KIND, NAMESPACE_VERSION};
use crate::store::{ObjectStore, ResourceKey};

/// Returns the built-in Namespace [`ResourceKey`] (re-exported here for clarity).
pub fn namespace_key() -> ResourceKey {
    crate::schema::namespace_key()
}

/// Returns the minimal JSON schema for the built-in Namespace resource.
///
/// The schema is intentionally minimal: `{"type": "object", "properties": {}}`.
/// Namespace objects carry no spec data — they are identified and managed via
/// `metadata` (name, labels, annotations). Keeping the spec schema empty
/// allows Namespace to flow through the normal validation path while leaving
/// room for future extension.
pub fn namespace_schema_json() -> Value {
    json!({
        "type": "object",
        "properties": {}
    })
}

/// Returns the [`ObjectMeta`] used to register the built-in Namespace schema.
///
/// The name format `"{Kind}.{group}.{version}"` matches the cache key
/// generated by [`crate::schema::schema_cache_key`], so registration and
/// lookup use the same identifier. `namespace: None` because Schema (and
/// therefore the Namespace schema registration) is cluster-scoped.
pub fn namespace_schema_meta() -> ObjectMeta {
    let name = crate::schema::schema_cache_key(NAMESPACE_KIND, NAMESPACE_GROUP, NAMESPACE_VERSION);
    ObjectMeta {
        name,
        namespace: None,
        labels: Default::default(),
        annotations: Default::default(),
        finalizers: Vec::new(),
    }
}

/// Registers the built-in Namespace schema with the given [`SchemaService`].
///
/// Idempotent: if a Namespace schema is already present (e.g. after server
/// restart with a persistent store), this is a no-op. The schema is registered
/// with `scope: "Cluster"` to match Namespace's cluster-scoped lifecycle.
///
/// Returns `Ok(())` on success. Returns an error if meta-schema validation
/// or compilation fails (should not happen for the built-in schema).
pub async fn register_namespace_schema(schema_service: &SchemaService) -> Result<(), AppError> {
    let key = crate::schema::schema_key();
    let meta = namespace_schema_meta();
    let spec = json!({
        "targetGroup": NAMESPACE_GROUP,
        "targetVersion": NAMESPACE_VERSION,
        "targetKind": NAMESPACE_KIND,
        "scope": "Cluster",
        "specSchema": namespace_schema_json(),
    });

    // Idempotent: skip if a Namespace schema is already registered.
    // SchemaService::get reads from the store (bypassing cache) so this
    // correctly detects pre-existing registrations on restart.
    if schema_service.get_validator(&namespace_key()).await.is_ok() {
        info!("Namespace schema already registered, skipping");
        return Ok(());
    }

    schema_service.create(key, meta, spec).await?;
    info!("Namespace schema registered");
    Ok(())
}

/// Bootstraps the `"default"` namespace object, creating it if it does not
/// already exist.
///
/// Uses the given `store` directly to check for existence (a single
/// `get` call) and to create the namespace object on first startup. Returns
/// `Ok(true)` if the namespace was created, `Ok(false)` if it already
/// existed.
///
/// Fails the server bootstrap if creation fails: callers (e.g. [`crate::bootstrap`])
/// should propagate this error so the server does not start in an inconsistent state.
///
/// The namespace object is stored with `metadata.namespace = None` (cluster-scoped)
/// and an empty spec object, matching the minimal Namespace schema.
pub async fn bootstrap_default_namespace(
    store: &Arc<dyn ObjectStore>,
    event_bus: &Arc<dyn EventPublisher>,
) -> Result<bool, AppError> {
    use crate::object::types::{StoredObject, SystemMetadata};

    let key = namespace_key();

    // Check if the "default" namespace already exists
    if store.get(&key, None, DEFAULT_NAMESPACE).await.is_ok() {
        info!(namespace = DEFAULT_NAMESPACE, "default namespace already exists");
        return Ok(false);
    }

    // Create the "default" namespace object
    let namespace_obj = StoredObject {
        key: key.clone(),
        metadata: ObjectMeta {
            name: DEFAULT_NAMESPACE.to_string(),
            namespace: None,
            labels: Default::default(),
            annotations: Default::default(),
            finalizers: Vec::new(),
        },
        system: SystemMetadata::initial(),
        spec: json!({}),
        status: None,
    };

    store.create(namespace_obj).await?;
    info!(namespace = DEFAULT_NAMESPACE, "default namespace created");

    // Publish a Namespace Added event so watchers of the Namespace kind see it
    event_bus.publish(
        &key,
        crate::object::types::WatchEvent {
            event_type: crate::object::types::WatchEventType::Added,
            object: store.get(&key, None, DEFAULT_NAMESPACE).await?,
        },
    );

    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::event::EventBus;
    use crate::event::EventPublisher;
    use crate::store::memory::InMemoryStore;
    use crate::store::sqlite::SQLiteStore;

    #[test]
    fn namespace_key_has_correct_group_version_kind() {
        let key = namespace_key();
        assert_eq!(key.kind, NAMESPACE_KIND);
        assert_eq!(key.group, NAMESPACE_GROUP);
        assert_eq!(key.version, NAMESPACE_VERSION);
    }

    #[test]
    fn namespace_schema_json_is_minimal_object() {
        let schema = namespace_schema_json();
        assert_eq!(schema["type"], "object");
        assert!(schema["properties"].is_object());
        assert!(schema["properties"].as_object().unwrap().is_empty());
    }

    #[test]
    fn namespace_schema_meta_uses_canonical_name() {
        let meta = namespace_schema_meta();
        assert_eq!(meta.name, "Namespace.kapi.io.v1");
        assert!(meta.namespace.is_none(), "Namespace schema metadata.namespace must be None");
    }

    async fn make_store_event_bus() -> (Arc<dyn ObjectStore>, Arc<dyn EventPublisher>) {
        let store: Arc<dyn ObjectStore> = Arc::new(InMemoryStore::new());
        let event_bus: Arc<dyn EventPublisher> = Arc::new(EventBus::default());
        (store, event_bus)
    }

    #[tokio::test]
    async fn bootstrap_creates_default_namespace_on_fresh_store() {
        let (store, event_bus) = make_store_event_bus().await;

        let created = bootstrap_default_namespace(&store, &event_bus)
            .await
            .expect("bootstrap should succeed");
        assert!(created, "expected default namespace to be created");

        // Verify the namespace exists in the store
        let obj = store
            .get(&namespace_key(), None, DEFAULT_NAMESPACE)
            .await
            .expect("default namespace should exist");
        assert_eq!(obj.metadata.name, DEFAULT_NAMESPACE);
        assert!(obj.metadata.namespace.is_none());
        assert_eq!(obj.system.resource_version, 1);
        assert_eq!(obj.system.generation, 1);
    }

    #[tokio::test]
    async fn bootstrap_is_idempotent_when_namespace_already_exists() {
        let (store, event_bus) = make_store_event_bus().await;

        // First bootstrap creates it
        bootstrap_default_namespace(&store, &event_bus).await.expect("first bootstrap");

        // Second bootstrap is a no-op
        let created =
            bootstrap_default_namespace(&store, &event_bus).await.expect("second bootstrap");
        assert!(!created, "second bootstrap should not recreate");

        // Still only one namespace object
        let list = store
            .list(&namespace_key(), None, crate::object::types::ListOptions::default())
            .await
            .expect("list should succeed");
        assert_eq!(list.items.len(), 1);
    }

    #[tokio::test]
    async fn bootstrap_works_with_sqlite_store() {
        let store: Arc<dyn ObjectStore> =
            Arc::new(SQLiteStore::new(":memory:").expect("sqlite open"));
        let event_bus: Arc<dyn EventPublisher> = Arc::new(EventBus::default());

        bootstrap_default_namespace(&store, &event_bus).await.expect("bootstrap should succeed");

        let obj = store
            .get(&namespace_key(), None, DEFAULT_NAMESPACE)
            .await
            .expect("default namespace should exist");
        assert_eq!(obj.metadata.name, DEFAULT_NAMESPACE);
    }
}
